from django.conf import settings


MULTISCHEMA_DEFAULT_NAMESPACE = str(getattr(settings, 'MULTISCHEMA_DEFAULT_NAMESPACE', 'public'))
MUTLISCHEMA_DEFAULT_NAMESPACE_FALLBACK = bool(getattr(settings, 'MUTLISCHEMA_DEFAULT_NAMESPACE_FALLBACK', False))
MULTISCHEMA_CREATE_IF_NOT_EXIST = bool(getattr(settings, 'MULTISCHEMA_CREATE_IF_NOT_EXIST', True))

MULTISCHEMA_SUPPORTED_BACKENDS = tuple(getattr(settings, 'MULTISCHEMA_SUPPORTED_BACKENDS', (
    'django.db.backends.postgresql_psycopg2',
)))


MULTISCHEMA_REVERSE_LOOKUP_HANDLER = getattr(settings, 'MULTISCHEMA_REVERSE_LOOKUP_HANDLER', 'multischema.reverse_lookup.mapping')
MULTISCHEMA_REVERSE_LOOKUP_DEFAULT = getattr(settings, 'MULTISCHEMA_REVERSE_LOOKUP_DEFAULT', None)
MULTISCHEMA_REVERSE_LOOKUP_DEFAULT_HANDLER = getattr(settings, 'MULTISCHEMA_REVERSE_LOOKUP_DEFAULT_HANDLER', lambda alias: alias)
MULTISCHEMA_REVERSE_LOOKUP_MAPPING = dict(getattr(settings, 'MULTISCHEMA_REVERSE_LOOKUP', {
    'default': MULTISCHEMA_DEFAULT_NAMESPACE,
}))



MULTISCHEMA_ALIAS_EXCLUDE = tuple(getattr(settings, 'MULTISCHEMA_ALIAS_EXCLUDE', (
    'default',
)))
